#!/bin/sh
# old way of doing it. There may be a benefit to doing it this way, so I'm leaving it in.
#PACKAGE=$(pkg search "-" | dmenu -l 20 | perl -ple 's/-\d.+//g') && pkg install $1  $PACKAGE 
pkg update >/dev/null && echo "updating repo if necessary"
PACKAGE=$(sqlite3 /var/db/pkg/repo-FreeBSD.sqlite 'select name,comment from packages;' | dmenu -l 20 | awk -F '|' '{ print $1 }') && pkg install $1  $PACKAGE 
